#! /usr/bin/env bash
echo "== put-object"

# Check for a bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket-my-bucket-name"
    exit 1
fi

# Check for a file name
if [ -z "$1" ]; then
    echo "There needs to be a file name eg. ./filename.txt"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY