#! /usr/bin/env bash
echo "== sync" 

# Exit immediately if any comand returns a non-zero status
set -e

# Check for a bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket-my-bucket-name"
    exit 1
fi

# Check for a filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a file name eg. file"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where we'll store these files
OUTPUT_DIR="/tmp"

## remove the folder if it already exists
sudo rm -rf $OUTPUT_DIR/*

# let's create output folder
mkdir -p $OUTPUT_DIR

# generate a random number
# to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=NUM_FILES; i++)); do
    RANDOM_FILENAME="$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt"

    dd if=/dev/urandom of="$RANDOM_FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files